python -u ./multi_domain/multi_domain_ner.py \
--architecture span \
--bert_config_file ./bert-base-chinese \
--data_dir ./data \
--domain msra*news*weibo \
--train \
--dev \
--test \
--output_dir ./output \
--max_len 200 \
--train_batch_size 25 \
--learning_rate 5e-5 \
--epoch 5 \
--test_batch_size 1 \
--tensorboard ./output/logs \
--dropout 0.2 \
--seed 1
